### ISSUE TITLE
ipapi has a fail that just blows up ...

### ISSUE THREAD

**Issue by grosser** [alexreisner/geocoder#1028]
geocoder-1.3.4/lib/geocoder/lookups/ipapi_com.rb:42:in `reserved_result' -> fail -> raises ...

https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/ipapi_com.rb#L42

```
vendor/bundle/ruby/2.2.0/gems/geocoder-1.3.4/lib/geocoder/lookups/ipapi_com.rb:42:in `reserved_result'
vendor/bundle/ruby/2.2.0/gems/geocoder-1.3.4/lib/geocoder/lookups/ipapi_com.rb:33:in `results'
vendor/bundle/ruby/2.2.0/gems/geocoder-1.3.4/lib/geocoder/lookups/base.rb:47:in `search'
vendor/bundle/ruby/2.2.0/gems/geocoder-1.3.4/lib/geocoder/query.rb:11:in `execute'
vendor/bundle/ruby/2.2.0/gems/geocoder-1.3.4/lib/geocoder.rb:22:in `search'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:198:in `process_action'
```

**Comment by TrangPham** [comment]
Thanks for reporting this! It should be fixed by https://github.com/alexreisner/geocoder/pull/1020 now
