### ISSUE TITLE
geocoder initializer error

### ISSUE THREAD

**Issue by muneeb2542** [alexreisner/geocoder#1050]
I am trying to create a geocoder.rb file by executing "rails generate geocoder:configure" and came across this error.
```
/home/maestro/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:29:in `require': incompatible library version - /home/maestro/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/nokogiri.so (LoadError)
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:29:in `rescue in <top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:25:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb:2:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/sanitize_helper.rb:3:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/sanitize_helper.rb:3:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/text_helper.rb:32:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/text_helper.rb:32:in `<module:TextHelper>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/text_helper.rb:29:in `<module:Helpers>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/text_helper.rb:6:in `<module:ActionView>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/text_helper.rb:4:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_tag_helper.rb:18:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_tag_helper.rb:18:in `<module:FormTagHelper>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_tag_helper.rb:14:in `<module:Helpers>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_tag_helper.rb:8:in `<module:ActionView>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_tag_helper.rb:6:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_helper.rb:4:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_helper.rb:4:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers.rb:50:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers.rb:50:in `<module:Helpers>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers.rb:4:in `<module:ActionView>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.6/lib/action_view/helpers.rb:3:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/context.rb:7:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/context.rb:7:in `<module:Context>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/context.rb:6:in `<module:Rails>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/context.rb:5:in `<module:Sprockets>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/context.rb:4:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:7:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:7:in `<top (required)>'
	from /home/maestro/evercam/evercam-dashboard/config/application.rb:6:in `require'
	from /home/maestro/evercam/evercam-dashboard/config/application.rb:6:in `<top (required)>'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `preload'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by TrangPham** [comment]
Hi @muneeb2542 

This is not an error with geocoder. The gem nokogiri is not part of geocoder's dependancies. 
Please try to reinstall nokogiri and then run the command again.

**Comment by muneeb2542** [comment]
Hi @TrangPham 

I did exactly what you asked me to do,i reinstalled nokogiri and ran the command again but now i'm getting this error

```
/home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client/run.rb:3:in `<top (required)>'
	from /home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client.rb:5:in `<top (required)>'
	from /home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/maestro/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/maestro/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/bin/spring:48:in `<main>'

```

**Comment by shakycode** [comment]
Did you by chance issue 'gem install bundler' under Ruby 2.3.0?  Skipping this step would cause that problem if bundler compiled for 2.3.0 is not installed.

**Comment by alexreisner** [comment]
Closing, as this appears to be an environment issue, but please reopen if there's evidence that Geocoder is the culprit.
