### ISSUE TITLE
Mongoid: NoMethodError: undefined method `each_pair' for

### ISSUE THREAD

**Issue by nirajmchauhan** [alexreisner/geocoder#1110]
I am getting following error when calling `Store.near(address)` 

Stacktrace:
```
NoMethodError: undefined method `each_pair' for "Whitefield":String
Did you mean?  each_char
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/mongoid-6.0.0/lib/mongoid/criteria/queryable/selectable.rb:616:in `block in selection'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/mongoid-6.0.0/lib/mongoid/criteria/queryable/selectable.rb:614:in `tap'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/mongoid-6.0.0/lib/mongoid/criteria/queryable/selectable.rb:614:in `selection'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/mongoid-6.0.0/lib/mongoid/criteria/queryable/mergeable.rb:177:in `__override__'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/mongoid-6.0.0/lib/mongoid/criteria/queryable/selectable.rb:337:in `near'
	from (eval):2:in `near'
	from (irb):18
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
... 1 levels...
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/commands/rails.rb:6:in `call'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:191:in `block in serve'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:161:in `fork'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:161:in `serve'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /Users/nirajmchauhan/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/nirajmchauhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nirajmchauhan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

My ruby version is: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
Rails 5.0.0.1
MongoDB shell version: 3.2.10

**Comment by alexreisner** [comment]
Geocoder removed support for `.near` queries with MongoDB (see #832), so your `.near` method is being provided by Mongoid. Please see their documentation for correct method arguments.

**Comment by nirajmchauhan** [comment]
But this means that mongo `$near` will only work if I pass latlong, what if I have address. 
How would that work? Earlier this gem use to convert Address to latlong and search results, correct me if I am wrong.

**Comment by alexreisner** [comment]
Yes, that's correct. With MongoDB now you'll have to geocode the address separately before running the query.

**Comment by nirajmchauhan** [comment]
This was one of the best feature and now its removed :( for mongo.
