### ISSUE TITLE
Can't chain `.near` with `.count`

### ISSUE THREAD

**Issue by Meekohi** [alexreisner/geocoder#1206]
### Expected behavior

`Venue.near("Portland, OR", 60, units: :mi).count`

Should return the number of venues within 60 miles of Portland, OR.

### Actual behavior

```
Venue.near("Portland, OR", 60, units: :mi).count
   (0.9ms)  SELECT COUNT(venues.*, 3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((45.507856 - venues.latitude) * PI() / 180 / 2), 2) + COS(45.507856 * PI() / 180) * COS(venues.latitude * PI() / 180) * POWER(SIN((-122.690794 - venues.longitude) * PI() / 180 / 2), 2))) AS distance, MOD(CAST((ATAN2( ((venues.longitude - -122.690794) / 57.2957795), ((venues.latitude - 45.507856) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing) FROM "venues" WHERE (venues.latitude BETWEEN 44.63946530133491 AND 46.376246698665085 AND venues.longitude BETWEEN -123.9299157125496 AND -121.45167228745039 AND (3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((45.507856 - venues.latitude) * PI() / 180 / 2), 2) + COS(45.507856 * PI() / 180) * COS(venues.latitude * PI() / 180) * POWER(SIN((-122.690794 - venues.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 60)
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "AS"
LINE 1: ...90794 - venues.longitude) * PI() / 180 / 2), 2))) AS distanc...
                                                             ^
: SELECT COUNT(venues.*, 3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((45.507856 - venues.latitude) * PI() / 180 / 2), 2) + COS(45.507856 * PI() / 180) * COS(venues.latitude * PI() / 180) * POWER(SIN((-122.690794 - venues.longitude) * PI() / 180 / 2), 2))) AS distance, MOD(CAST((ATAN2( ((venues.longitude - -122.690794) / 57.2957795), ((venues.latitude - 45.507856) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing) FROM "venues" WHERE (venues.latitude BETWEEN 44.63946530133491 AND 46.376246698665085 AND venues.longitude BETWEEN -123.9299157125496 AND -121.45167228745039 AND (3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((45.507856 - venues.latitude) * PI() / 180 / 2), 2) + COS(45.507856 * PI() / 180) * COS(venues.latitude * PI() / 180) * POWER(SIN((-122.690794 - venues.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 60)
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
  from .../activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  from .../activerecord-4.2.8/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
  from .../activerecord-4.2.8/lib/active_record/relation/calculations.rb:270:in `execute_simple_calculation'
  from .../activerecord-4.2.8/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
  from .../activerecord-4.2.8/lib/active_record/relation/calculations.rb:133:in `calculate'
  from .../activerecord-4.2.8/lib/active_record/relation/calculations.rb:48:in `count'
  from (irb):6
... 1 levels...
  from .../railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
  from .../railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
  from .../railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from .../railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  from .../bin/rails:8:in `<top (required)>'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  from .../activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
  from /home/ec2-user/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/ec2-user/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from -e:1:in `<main>'
```

### Steps to reproduce

Can test on console: `Venue.near("Portland, OR", 60, units: :mi).count`

### Environment info

Geocoder version: 1.4.3
Rails version: 4.2.8
Database (if applicable): Postgresql (not sure if this is PG specific or not)

**Comment by alexreisner** [comment]
[Try using `count(:all)` instead.](https://github.com/alexreisner/geocoder#note-on-rails-41-and-greater)

**Comment by Meekohi** [comment]
Man it's like the first paragraph in the docs too... Thanks!
