### ISSUE TITLE
OpenSSL Error on geocoded model creation when upgrading from 1.4.4 to 1.4.6 (custom nominatim server with no HTTPS)

### ISSUE THREAD

**Issue by sipox11** [alexreisner/geocoder#1275]
### Expected behavior

When I create a new record of a geocoded model, it should create it and populate the geocoded fields correctly. That was the behaviour until I updated the gem from 1.4.4 to 1.4.6.

```
Spot.create({latitude: 40.40, longitude: -3.3})
```
This should succeed, just like it did before the gem version upgrade.

### Actual behavior

When I upgraded the gem to 1.4.6 I started getting the following error while attempting to create a new record of a geocoded model: 

```
Spot.create({latitude: 40.40, longitude: -3.3})
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `call'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:583:in `start'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/geocoder-1.4.6/lib/geocoder/lookups/base.rb:276:in `make_api_request'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/geocoder-1.4.6/lib/geocoder/lookups/base.rb:226:in `fetch_raw_data'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/geocoder-1.4.6/lib/geocoder/lookups/base.rb:177:in `fetch_data'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/geocoder-1.4.6/lib/geocoder/lookups/nominatim.rb:28:in `results'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/geocoder-1.4.6/lib/geocoder/lookups/base.rb:47:in `search'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/geocoder-1.4.6/lib/geocoder/query.rb:11:in `execute'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/geocoder-1.4.6/lib/geocoder.rb:22:in `search'
... 22 levels...
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:286:in `block in save'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:285:in `save'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/associations/singular_association.rb:73:in `_create_record'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/associations/singular_association.rb:21:in `create'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/associations/builder/singular_association.rb:22:in `create_spot'
	from (irb):4
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/deploy/var/www/pf/preproduction/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
```

### Steps to reproduce

From a working setup for a geocoded model, upgrade from 1.4.4 to 1.4.6 and it stops working. I use a custom nominatim server running on my own server, with no HTTPS (I set it to false in the initializer config file).

I temporarily locked the gem version to 1.4.4 in my Gemfile just like it was, with no further configuration made and everything is back to normal. 

### Environment info

* Geocoder version: 1.4.6
* Rails version: 4.2.4
* Ruby version: 2.2.0
* Database (if applicable): postgresql

**Comment by alexreisner** [comment]
Sorry, this is a bug. New gem release (1.4.7) coming today. (See also #1267.)
