### ISSUE TITLE
Error setting up cache expiration error: Redis::CommandError (ERR unknown command '[]')

### ISSUE THREAD

**Issue by auvi** [alexreisner/geocoder#1278]
I am trying to setup expiring Redis cache but I get errors. Below is the setup and an IRB session.
```ruby
#File: config/initializers/redis_and_others.rb:
$kvs = Redis.new(:url => ENV["REDISCLOUD_URL"])

class AutoexpireCacheRedis
  def initialize(store, ttl = 7.days.to_i)
    @store = store
    @ttl = ttl
  end

  def [](url)
    @store.[](url) # <---- The offending line
  end

  def []=(url, value)
    @store.[]=(url, value)
    @store.expire(url, @ttl)
  end

  def keys
    @store.keys
  end

  def del(url)
    @store.del(url)
  end
end

Geocoder.configure({
  :ip_lookup => :maxmind_geoip2,
  :cache => AutoexpireCacheRedis.new($kvs),
  :maxmind_geoip2 => {
    :service => :city,
    :basic_auth => {
      :user => "example",
      :password => "*******"
    }
  }
})

# in Rails console
> Geocoder::Query.new('139.130.4.5').execute
Traceback (most recent call last):
        2: from (irb):2
        1: from config/initializers/redis_and_others.rb:15:in `[]'
Redis::CommandError (ERR unknown command '[]')
```

Any idea what's wrong?

**Comment by alexreisner** [comment]
What version of the Redis client gem are you using? Can you open an IRB session, create a new client, and see how it responds to the `[]` method?

**Comment by auvi** [comment]
I'm using redis client gem version 4.0.1
```ruby
$ bundle exec rails c
Loading development environment (Rails 5.1.5)
2.5.0 :001 > $redis = Redis.new(:url => ENV["REDISCLOUD_URL"])
=> #<Redis client v4.0.1 for redis://redacted:13675/0> 
2.5.0 :002 > cache = AutoexpireCacheRedis.new($redis)
=> #<AutoexpireCacheRedis:0x00007faa6f009058 @store=#<Redis client v4.0.1 for redis://redacted:13675/0>, @ttl=604800> 
2.5.0 :003 > cache['foo']
Traceback (most recent call last):
       2: from (irb):3
       1: from config/initializers/redis_and_others.rb:15:in `[]'
Redis::CommandError (ERR unknown command '[]')
2.5.0 :004 > 
```

**Comment by alexreisner** [comment]
Looks like [those methods were removed in redis-rb gem version 4.0](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#40). You'll have to adjust your cache class accordingly (use `set` and `get` instead). I just updated [the example file](https://github.com/alexreisner/geocoder/blob/master/examples/autoexpire_cache_redis.rb) to reflect this change.

Thanks for pointing this out.
