### ISSUE TITLE
Geocoder on heroku with QuotaGuard

### ISSUE THREAD

**Issue by benoittgt** [alexreisner/geocoder#817]
Hello

I'm using geocoder with gmap4rails for finding position from a string address like `"12 rue de Rivoli Paris"`. It's work perfectly localy but I get some crash when the app are deploy on heroku because of the API limit. So I've follow [the tutorial on heroku](https://devcenter.heroku.com/articles/quotaguard) to fix this with QuotaGuard.Adding a `:http_proxy => ENV['QUOTAGUARD_URL'],` with the proper value in the geocoder initiliazer. The thing is when I'm doing this, in rail console on Heroku If I run : `Geocoder.search("12 rue de Rivoli Paris")` I get `Geocoding API's response was not valid JSON. => [] `.

If I add `:always_raise => all` to the initializer (like mention in https://github.com/alexreisner/geocoder/pull/768) : 
```
Running `rails console` attached to terminal... up, run.8280
Loading production environment (Rails 4.2.0)
irb(main):001:0> Geocoder.search("12 rue de Rivoli Paris")
Geocoder::ResponseParseError: Geocoder::ResponseParseError
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:159:in `raise_error'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:186:in `rescue in parse_json'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:180:in `parse_json'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:193:in `parse_raw_data'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:169:in `fetch_data'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/lookups/google.rb:28:in `results'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:47:in `search'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder/query.rb:11:in `execute'
from /app/vendor/bundle/ruby/2.0.0/gems/geocoder-1.2.7/lib/geocoder.rb:20:in `search'
from (irb):1
from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in     `run_command!'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
from /app/bin/rails:8:in `require'
from /app/bin/rails:8:in 
```

So I was wondering if it's related to quotaguard (I've contacted them too), or geocoder ?

Off topic: @alexreisner I love [your photos](http://www.alexreisner.com/photos)!

**Comment by benoittgt** [comment]
Hello

I get and answer for quotaguard : 
```shell
irb(main):032:0> Geocoder::Lookup.get(:google).send(:fetch_raw_data, Geocoder::Query.new("12 rue de Rivoli Paris"))
=> "status: PROXY_OVER_QUERY_LIMIT"
```

Problem was simply because I've hit the 25 requests limit. To check with a little script, Tim for QuotaGuard give me this tips : 
```ruby
require "rest-client"

RestClient.proxy = ENV["QUOTAGUARD_URL"] if ENV["QUOTAGUARD_URL"]

def over_quotaguard_limit?
 res = RestClient.get("http://maps.googleapis.com/maps/api/geocode/json?address=13794&language=en&sensor=false")
 if res.include? "PROXY_OVER_QUERY_LIMIT"
  puts "You're over the daily limit!"
  return true
 end
 return false
end

puts over_quotaguard_limit?
```
