### ISSUE TITLE
no implicit conversion of Pathname into String

### ISSUE THREAD

**Issue by fero46** [alexreisner/geocoder#852]
After some time gecoder didn't work for me anymore. I got strange Message: "no implicit conversion of Pathname into String".  Here is my Rails Console:

```
Loading development environment (Rails 4.1.9)
irb(main):001:0> a=Account.find(6)
...
irb(main):002:0> a.update "street_number"=>"40"
   (0.2ms)  BEGIN
  User Load (0.4ms)  SELECT `users`.* FROM `users`  WHERE `users`.`account_id` = 6
  Account Load (0.3ms)  SELECT  `accounts`.* FROM `accounts`  WHERE `accounts`.`id` = 6 LIMIT 1
   (0.3ms)  ROLLBACK
TypeError: no implicit conversion of Pathname into String
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:895:in `initialize'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:895:in `new'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:895:in `connect'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:583:in `start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:268:in `block in make_api_request'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:266:in `make_api_request'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:218:in `fetch_raw_data'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:169:in `fetch_data'
```

My Gecoder Config looks like this:

```ruby
Geocoder.configure(
  :lookup       => :google, 
  :language     => :de, 
  :api_key      => Settings.map_key, 
  :cache        => Redis.new, 
  :cache_prefix => "bushunter:",
  :use_https => true,
  :units     => :km,
)
```

Does anyone have an Idea ?

**Comment by alexreisner** [comment]
This sounds more like a problem with how you're storing data in your application. It's hard to tell from what you've posted. Maybe try StackOverflow?

**Comment by fero46** [comment]
No I don't think so because I got the same problem when i try the example from the Site:
```
Loading development environment (Rails 4.1.9)
irb(main):001:0> Geocoder.coordinates("25 Main St, Cooperstown, NY")
TypeError: no implicit conversion of Pathname into String
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:895:in `initialize'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:895:in `new'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:895:in `connect'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:583:in `start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:270:in `block in make_api_request'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:263:in `make_api_request'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:218:in `fetch_raw_data'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:169:in `fetch_data'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder/lookups/google.rb:28:in `results'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder/lookups/base.rb:47:in `search'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder/query.rb:11:in `execute'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder.rb:20:in `search'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/geocoder-1.2.7/lib/geocoder.rb:27:in `coordinates'
	from (irb):1
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:90:in `start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:9:in `start'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/fero46/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'irb(main):002:0> 
```

**Comment by alexreisner** [comment]
Ah, okay, that looks very different.

**Comment by fero46** [comment]
I Got the same problem when I use this configuration without api_key
```ruby
Geocoder.configure(
  :lookup       => :google, 
  :language     => :de, 
  :cache        => Redis.new, 
  :cache_prefix => "bushunter:",
  :use_https => true,
  :units     => :km,
)
```
But when I disable https, it works.

```ruby
Geocoder.configure(
  :lookup       => :google, 
  :language     => :de, 
  :cache        => Redis.new, 
  :cache_prefix => "bushunter:",
  :use_https => false,
  :units     => :km,
)
```

**Comment by alexreisner** [comment]
@fero46 thanks, that's very helpful.

**Comment by TrangPham** [comment]
I was not able to reproduce your issue. @alexreisner Were you able to see this error?

``` Ruby
Thus-MacBook-Air:geocoder trangpham$ irb
2.1.2 :001 > require 'geocoder'
 => true
2.1.2 :002 > require 'redis'
 => true
2.1.2 :003 > Geocoder.configure(
2.1.2 :004 >       :lookup       => :google,
2.1.2 :005 >       :language     => :de,
2.1.2 :006 >       :cache        => Redis.new,
2.1.2 :007 >       :cache_prefix => "bushunter:",
2.1.2 :008 >       :use_https => true,
2.1.2 :009 >       :units     => :km,
2.1.2 :010 >     )
 => {:timeout=>3, :lookup=>:google, :ip_lookup=>:freegeoip, :language=>:de, :http_headers=>{}, :use_https=>true, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>#<Redis client v3.1.0 for redis://127.0.0.1:6379/0>, :cache_prefix=>"bushunter:", :basic_auth=>{}, :logger=>:kernel, :kernel_logger_level=>2, :always_raise=>[], :units=>:km, :distances=>:linear}
2.1.2 :011 > Geocoder.coordinates("25 Main St, Cooperstown, NY")
 => [42.6997009, -74.9232415]
2.1.2 :012 > exit
```

**Comment by alexreisner** [comment]
@TrangPham: I have not been able to reproduce. I think we need more information about his environment. @fero46: any update on this? Is it still happening? If so could you post your `Gemfile`? Also, have you had this problem in other apps?
