### ISSUE TITLE
Yahoo error

### ISSUE THREAD

**Issue by erdostom** [alexreisner/geocoder#867]
Hello, I signed up for a fresh Yahoo BOSS account, and I'm getting the following error when I try to geocode an address:

````
NoMethodError: undefined method `[]' for nil:NilClass
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/geocoder/lookups/yahoo.rb:33:in `results'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:47:in `search'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/geocoder/query.rb:11:in `execute'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/geocoder.rb:21:in `search'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/geocoder/stores/base.rb:111:in `do_lookup'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/geocoder/stores/active_record.rb:259:in `geocode'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/tasks/geocoder.rake:12:in `block (3 levels) in <top (required)>'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:51:in `each'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/activerecord-
4.2.1/lib/active_record/relation/batches.rb:51:in `block in find_each'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:50:in `find_each'
/Users/TamasErdos/.rvm/gems/ruby-2.2.1/gems/geocoder-1.2.8/lib/tasks/geocoder.rake:11:in `block (2 levels) in <top (required)>
````

Here is my config:
````
Geocoder.configure(
  # geocoding options
  :timeout      => 3,           # geocoding service timeout (secs)
  :lookup       => :yahoo,     # name of geocoding service (symbol)
  yahoo: { api_key: [ENV["YAHOO_API_KEY"], ENV["YAHOO_API_SECRET"]]},
   :use_https    => true,       # use HTTPS for lookup requests? (if supported)
  :cache        => REDIS,         # cache object (must respond to #[], #[]=, and #keys)
) unless Rails.env.test?
````

**Comment by alexreisner** [comment]
Can you try the suggestions listed [in the README](https://github.com/alexreisner/geocoder#unexpected-responses-from-geocoding-services) and see if that gives any insight?

**Comment by erdostom** [comment]
This is freaky, I just put in ` always_raise: :all` and it immediately started working. Maybe the API needed some time to provision..

Thank you for following up so quickly!
