### ISSUE TITLE
Error when using auto cache expiration example

### ISSUE THREAD

**Issue by flynfish** [alexreisner/geocoder#868]
Getting an error trying to use the example:

```ruby
class AutoexpireCacheRedis
  def initialize(store, ttl = 3.days.to_i)
    @store = store
    @ttl = ttl
  end

  def [](url)
    @store.[](url)
  end

  def []=(url, value)
    @store.[]=(url, value)
    @store.expire(url, @ttl)
  end

  def keys
    @store.keys
  end

  def del(url)
    @store.del(url)
  end
end

Geocoder.configure(
  :cache        => AutoexpireCacheRedis.new($redis), # cache object (must respond to #[], #[]=, and #keys)
)
```

```ruby
a = Address.last
a.save
```

```
NoMethodError: undefined method `[]' for nil:NilClass
	from /var/www/cfs-web/config/initializers/geocoder.rb:11:in `[]'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/cache.rb:15:in `[]'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:214:in `fetch_raw_data'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:169:in `fetch_data'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/lookups/google.rb:28:in `results'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:47:in `search'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/query.rb:11:in `execute'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder.rb:21:in `search'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/stores/base.rb:111:in `do_lookup'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/geocoder-1.2.8/lib/geocoder/stores/active_record.rb:259:in `geocode'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:416:in `_run__1529597759550700836__validation__415420391470866939__callbacks'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_validation_callbacks'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activemodel-3.2.19/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activemodel-3.2.19/lib/active_model/validations.rb:195:in `valid?'
... 2 levels...
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/validations.rb:50:in `save'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/attribute_methods/dirty.rb:22:in `save'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/transactions.rb:208:in `transaction'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/transactions.rb:259:in `block in save'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/activerecord-3.2.19/lib/active_record/transactions.rb:258:in `save'
	from (irb):2
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
	from /usr/local/rvm/gems/ruby-2.1.2@cfs-web/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

It works fine when just using:
```ruby
Geocoder.configure(
  :cache        => $redis, # cache object (must respond to #[], #[]=, and #keys)
)
```

**Comment by flynfish** [comment]
The issue is that geocoder initializer gets loaded before the redis.rb initializer which sets the $redis variable. 

To fix you can add this in the geocoder.rb initializer:
```ruby
require_relative 'redis'
```
