### ISSUE TITLE
yandex geocoding error

### ISSUE THREAD

**Issue by donbobka** [alexreisner/geocoder#875]
Geocoding with yandex failed with exception due to redirect to https: 
https://www.youtube.com/watch?v=euYYbQduCBk&feature=youtube_gdata

Should we follow redirects?

```
D, [2015-06-23T15:07:08.256427 #24782] DEBUG -- : Geocoder: HTTP request being made for http://geocode-maps.yandex.ru/1.x/?format=json&geocode=%D0%B3+%D0%92%D0%B5%D1%80%D1%85%D0%BD%D1%8F%D1%8F+%D0%9F%D1%8B%D1%88%D0%BC%D0%B0%2C+%D1%83%D0%BB+%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D0%B0%2C+56+&plng=ru
/Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:166:in `raise_error': undefined method `include?' for true:TrueClass (NoMethodError)
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:194:in `rescue in parse_json'
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:188:in `parse_json'
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:201:in `parse_raw_data'
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:177:in `fetch_data'
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/lookups/yandex.rb:22:in `results'
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:47:in `search'
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder/query.rb:11:in `execute'
	from /Users/donbobka/Desktop/check_geo_objects/.bundle/gems/geocoder-1.2.9/lib/geocoder.rb:21:in `search'
```

**Comment by donbobka** [comment]
Fix https://github.com/alexreisner/geocoder/pull/876
