### ISSUE TITLE
Stubbing invalid address coordinates request

### ISSUE THREAD

**Issue by sromocki** [alexreisner/geocoder#903]
Hello!

I'm looking to stub an invalid address for the Geocoder.coordinates(address) call.
If I call:

```point = Geocoder.coordinates("sadjdasks")```

point returns as nil

In order to stub a request like this I have tried the following code:

```
Geocoder::Lookup::Test.add_stub("sadjdasks", [])  # returns with error, undefined 'each_key'
Geocoder::Lookup::Test.add_stub("sadjdasks", [{}]) # returns [0.0,0.0]
Geocoder::Lookup::Test.add_stub("sadjdasks", nil) # returns with error, undefined 'map'
```

Perhaps, within results/test.rb you can check to see if data exists.  If not, then return nil.

Thanks!

**Comment by alexreisner** [comment]
Great point. Open to a pull request. I think the correct way to specify no results should be:

    Geocoder::Lookup::Test.add_stub("sadjdasks", []) # empty array

as that is what `Lookup::Base#results` returns.

**Comment by TrangPham** [comment]
@sromocki Hi I tried to reproduce your issue using ruby 2.1.2 and geocoder 1.2.11

This is the result I got:
```ruby
$ irb
2.1.2 :001 > require 'geocoder'
 => true
2.1.2 :003 > Geocoder.configure(:lookup => :test)
 => {:timeout=>3, :lookup=>:test, :ip_lookup=>:freegeoip, :language=>:en, :http_headers=>{}, :use_https=>false, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>nil, :cache_prefix=>"geocoder:", :basic_auth=>{}, :logger=>:kernel, :kernel_logger_level=>2, :always_raise=>[], :units=>:mi, :distances=>:linear}
2.1.2 :004 > Geocoder::Lookup::Test.add_stub("1", [])
 => []
2.1.2 :005 > Geocoder::Lookup::Test.add_stub("2", [{}])
 => [{}]
2.1.2 :006 > Geocoder::Lookup::Test.add_stub("3", nil)
 => nil
2.1.2 :008 > Geocoder.search("1")
 => []
2.1.2 :009 > Geocoder.search("2")
 => [#<Geocoder::Result::Test:0x007fe54cafac60 @data={}, @cache_hit=nil>]
2.1.2 :010 > Geocoder.search("3")
NoMethodError: undefined method `map' for nil:NilClass
	from /Users/trangpham/.rvm/gems/ruby-2.1.2/gems/geocoder-1.2.11/lib/geocoder/lookups/base.rb:47:in `search'
	from /Users/trangpham/.rvm/gems/ruby-2.1.2/gems/geocoder-1.2.11/lib/geocoder/query.rb:11:in `execute'
	from /Users/trangpham/.rvm/gems/ruby-2.1.2/gems/geocoder-1.2.11/lib/geocoder.rb:22:in `search'
	from (irb):10
	from /Users/trangpham/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
2.1.2 :011 > Geocoder.coordinates("1")
 => nil
2.1.2 :012 > Geocoder.coordinates("2")
 => [0.0, 0.0]
2.1.2 :013 > Geocoder.coordinates("3")
NoMethodError: undefined method `map' for nil:NilClass
	from /Users/trangpham/.rvm/gems/ruby-2.1.2/gems/geocoder-1.2.11/lib/geocoder/lookups/base.rb:47:in `search'
	from /Users/trangpham/.rvm/gems/ruby-2.1.2/gems/geocoder-1.2.11/lib/geocoder/query.rb:11:in `execute'
	from /Users/trangpham/.rvm/gems/ruby-2.1.2/gems/geocoder-1.2.11/lib/geocoder.rb:22:in `search'
	from /Users/trangpham/.rvm/gems/ruby-2.1.2/gems/geocoder-1.2.11/lib/geocoder.rb:29:in `coordinates'
	from (irb):13
	from /Users/trangpham/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

It would seem that `Geocoder::Lookup::Test.add_stub("sadjdasks", []) # empty array` would work without changes to the code base. (See `"1"` in the above output)

**Comment by sromocki** [comment]
@TrangPham I tried this again and it worked fine.  I may have made some mistake previously.  I think this can be closed.
