### ISSUE TITLE
Latest 1.2.10 version crash on starting up - Uncaught exception: uninitialized constant Timeout

### ISSUE THREAD

**Issue by libin0120** [alexreisner/geocoder#907]
With the latest update to 1.2.10, our server got this crash on starting up: 
```
Uncaught exception: uninitialized constant Timeout

	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/geocoder-1.2.10/lib/geocoder/exceptions.rb:32:in `<module:Geocoder>'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/geocoder-1.2.10/lib/geocoder/exceptions.rb:1:in `<top (required)>'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/geocoder-1.2.10/lib/geocoder.rb:6:in `<top (required)>'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
	C:/software/ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
```

**Comment by alexreisner** [comment]
It looks like you're missing the `Timeout` class, which is odd because it's entirely separate from Geocoder (Ruby std lib). I can't figure out how an upgrade to 1.2.10 would cause this issue. Could you take a look at [the changeset](https://github.com/alexreisner/geocoder/compare/v1.2.9...v1.2.10) and see if you can spot anything?

**Comment by nicolaslechenic** [comment]
I have the same problem, geocoder works well in 1.2.9 but with the same error in 1.2.10:
Ruby: 1.9.3
Rails: 3.2.17

**Comment by alexreisner** [comment]
Ah, I see. Sorry about that. Please try installing from current head:

    gem 'geocoder', github: 'alexreisner/geocoder'

Let me know if that solves it and I'll re-release.

**Comment by nicolaslechenic** [comment]
It works for me, thanks !

**Comment by alexreisner** [comment]
Version 1.2.11 released. My bad. Thanks again!
